language: php
php:
  - '7.0'
  - '5.6'
  - '5.5'
install:
  - 'cd _add-ons/imgix && composer install'
script: 'echo "Tests pending a harness from Statamic. imgix-php is well-tested though, and that''s there most of imgix-statamic''s logic lives."'
